---
- name: Install Apache with custom port
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Update package repository
      yum:
        name: "*"
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Change Apache port in ports.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^Listen 80"
        line: "Listen 8081"

    - name: Update VirtualHost port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "<VirtualHost _default_:80>"
        line: "<VirtualHost _default_:8081>"

    - name: Restart Apache to apply changes
      service:
        name: httpd
        state: restarted
